### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/libgit2#10]
* [ ] `lg2 status` is very slow on iOS.
     * `dulwich status` was also very slow.
     * It looks like this isn't just an iOS issue: https://github.com/libgit2/libgit2/issues/4230
 * [x] I don't see `lg2 branch` in build 172. [**Resolved**]
 * [x] `lg2 rm` (though `lg2 add -u` should remove items from the index...)
     * Really, this is **half-done**. Only `lg2 rm --cached` works properly. See https://github.com/holzschu/libgit2/pull/7
 * [ ] `lg2 log` logs **everything**
     * One solution could be to have a default number of commits to log (and a command-line option that allows the user to log more).
     * Not a big issue currently -- users can run `lg2 log | less`.
 * [x] `lg2 submodule`
     * This PR seems to add support for the `submodule` command: https://github.com/libgit2/libgit2/pull/4712
     * See #13
 * [x] `lg2 checkout -- file1 file2 file3...`
     * [ ] `lg2 checkout -- file1 file2 file3...` without `--force`
 * [x] `lg2 rebase`
 * [ ] `lg2 rebase -i` (Interactive rebase.)
     * It looks like `libgit2` doesn't have support for interactive re-basing: https://github.com/libgit2/libgit2/issues/3795
 * [x] `lg2 apply`
 * [x] `lg2 commit`: Creating an empty commit (nothing staged) should be an error. (https://github.com/holzschu/libgit2/pull/7)
 * [x] `lg2 stash drop`
 * [ ] `lg2 config --global`
     * [x] Workaround: `lg2 config` prints the path of the global configuration file in its output.
 * [x] `lg2 commit`, `lg2 stash` inform the user that author information (`user.email`, etc) is not found, with no explanation of how to fix this.
     * Suggests that users run `lg2 config user.email myemail@example.com`, `lg2 config user.name 'My Name'`, etc., or interactively prompt them.
 * [x] Make `lg2 add`, `lg2 status`, `lg2 reset` use the current working directory, instead of being relative to the repository's base directory.
 * [ ] `lg2 merge --abort` and `lg2 reset --hard` (#15)
 * [x] Add `lg2 push --force`
     * Users can also use `lg2 push origin +refs/heads/branch_name_here`.
 * [x] Fix: Certificate validation always says `invalid certificate` when I listen for the callback (as in `lg2 push`).
     * [x] It has a memory leak, though! Call [`libssh2_knownhost_free`](https://libssh2.org/libssh2_knownhost_free.html) on the list of known hosts!
         * See #11
 * [x] Make `ssh` key selection display a list of suggested keys
 * [ ] Colorized output
 * [ ] Open `vim` to edit commit messages
     * Will require `ios_system`/switching `a-Shell` to interactive mode.
